### ISSUE TITLE
Tracking issue: perl packages wrong arch

### ISSUE THREAD

**Issue by yopito** [voidlinux/void-packages#15056]
Following issue #15044: some perl package has wrong arch:

1. must have an arch != noarch since they contain binary files (like ELF)
- [x] perl-Class-XSAccessor-1.19_1 PR #15055 
- [x] perl-Socket-MsgHdr-0.04_1 PR #15059
- [x] perl-Taint-Runtime-0.03_1 PR #15060
- [x] perl-Template-Toolkit-2.27_1 PR #15061
- [x] perl-Text-Bidi-2.12_3 PR #15062
- [x] perl-YAML-LibYAML-0.69_1 PR #15042 

2. must be `noarch` since they don't contain binary files (like ELF)
- [x] perl-Class-Accessor-0.51_1
- [x] perl-Clone-Choose-0.008_1
- [x] perl-Clone-PP-1.07_1
- [x] perl-Data-Section-Simple-0.07_1
- [x] perl-File-Slurper-0.012_1
- [x] perl-IO-CaptureOutput-1.1104_1
- [x] perl-IO-HTML-1.001_1
- [x] perl-IO-SessionData-1.03_1
- [x] perl-Importer-0.025_1
- [x] perl-Mail-POP3Client-2.19_1
- [x] perl-Mail-Sendmail-0.80_1
- [x] perl-Module-Pluggable-5.2_1
- [x] perl-Net-DNS-1.15_1
- [x] perl-Net-IMAP-Client-0.9505_1
- [x] perl-PatchReader-0.9.6_1
- [x] perl-SUPER-1.20141117_1
- [x] perl-Spiffy-0.46_1
- [x] perl-Stream-Buffered-0.03_1
- [x] perl-Sub-Info-0.002_1
- [x] perl-Test-Base-0.89_1
- [x] perl-Test-CPAN-Meta-0.25_1
- [x] perl-Test-Cmd-1.09_1
- [x] perl-Test-Deep-1.128_1
- [x] perl-Test-FailWarnings-0.008_1
- [x] perl-Test-MockModule-0.15_1
- [x] perl-Test-Most-0.35_1
- [x] perl-Test-Needs-0.002005_1
- [x] perl-Test-Output-1.031_1
- [x] perl-Test-Requires-0.10_1
- [x] perl-Test-RequiresInternet-0.05_1
- [x] perl-Test-Subroutines-1.113350_1
- [x] perl-Test-Weaken-3.022000_1
- [x] perl-Test-YAML-1.06_1
- [x] perl-Text-XLogfile-0.06_1
- [x] perl-WebService-MusicBrainz-1.0.4_1
- [x] perl-XML-Parser-Lite-0.721_1
- [x] perl-CPAN-Meta-Check-0.014_1 PR #15098
- [x] perl-CheckLib-1.07_1 ... orphaned package (no template)
- [x] perl-Config-Simple-4.58_1 PR #15098
- [x] perl-Net-MPD-0.07_1 PR #15098
- [x] perl-Test-Warnings-0.026_1 PR #15098

**Comment by maxice8** [comment]
i'll fix the ones i maintain.

**Comment by maxice8** [comment]
https://github.com/voidlinux/void-packages/pull/15070

**Comment by newbluemoon** [comment]
#15086 fixes the remaining packages from the list above. perl-Test-Output has already been fixed, just the tick has been forgotten. ;)

**Comment by yopito** [comment]
what a success for this issue ;) many thanks for your prompt fixes !
I've just rerun against the 360 perl-* packages of x86_64 as of now.  
I found the following (replace initial listing).  Seems to comes from new merged packages from the last 24 hours:

1. package that must have an arch != noarch since they contain binary files (like ELF)
(none)

2. must be noarch since they don't contain binary files (like ELF)
- [ ] perl-CPAN-Meta-Check-0.014_1
- [ ] perl-CheckLib-1.07_1
- [ ] perl-Config-Simple-4.58_1
- [ ] perl-Net-MPD-0.07_1
- [ ] perl-Test-Warnings-0.026_1

**Comment by maxice8** [comment]
@yopito https://github.com/voidlinux/void-packages/pull/15098

couuldn't find perl-CheckLib

**Comment by yopito** [comment]
package `perl-CheckLib` : package source has been renamed, but the old package is still present in repo.  
What do do: another issue to request removal from repo ?

```
commit 19fd30db10ea62d61519e06efd175af5cdd1d0a0
Author: Alessio Sergi <al3hex@gmail.com>
Date:   Mon Apr 10 12:28:57 2017 +0200

    perl-CheckLib: update to 1.09, renamed to perl-Devel-CheckLib, noarch=yes

R051    srcpkgs/perl-CheckLib/template  srcpkgs/perl-Devel-CheckLib/template
```

```
 xbps-query -R perl-CheckLib-1.07_1
architecture: x86_64
build-date: 2017-03-14 16:18 CET
filename-sha256: 8b9ddc9a99e6a946c153a58cc68d08d8898ec8cf32cdcdd2303a8d72cc2ac299
filename-size: 9924B
homepage: http://search.cpan.org/dist/Devel-CheckLib/
installed_size: 34KB
license: Artistic, GPL-1
maintainer: Sir_Boops <admin@boops.me>
pkgver: perl-CheckLib-1.07_1
repository: https://repo.voidlinux.eu/current
short_desc: Module to check for other perl modules
source-revisions: perl-CheckLib:fe81cc6bf5
```

**Comment by yopito** [comment]
updated as of now: no changes. refactored list.

**Comment by yopito** [comment]
all fine.
