### ISSUE TITLE
Tracking bug: Remove systemd support

### ISSUE THREAD

**Issue by thypon** [voidlinux/void-packages#1736]
Right now the systemd support is disfunctional and it's there only to clutter our srcpkgs, why we don't remove it?

EDIT:
Given we agreed on systemd support removal these packages still have systemd support:

- [X] ModemManager
- [X] NetworkManager
- [ ] accountsservice
- [ ] base-system
- [ ] cairo-dock-plugins
- [ ] cinnamon-control-center
- [ ] cinnamon-settings-daemon
- [ ] fprintd
- [X] gdm
- [ ] gnome-disk-utility
- [ ] gnome-system-monitor
- [ ] gvfs
- [ ] kde
- [X] kde-workspace
- [ ] liblogging
- [X] lightdm
- [X] lxdm
- [ ] mate
- [ ] mate-accountsdialog
- [X] polkit
- [ ] procps-ng
- [ ] pulseaudio
- [ ] rpcbind
- [ ] slim
- [X] subversion
- [ ] upower
- [ ] upower0
- [ ] usbmuxd
- [ ] xfce4
- [ ] xfce4-power-manager
- [ ] xorg-server1.16

**Comment by derlaft** [comment]
I was hoping to try fixing the most basic stuff one day

**Comment by xtraeme** [comment]
I have to agree with @thypon ... our systemd pkg is completely broken and it's unlikely that somebody will resurrect it.

I don't really need systemd anymore :+1:

**Comment by beefcurtains** [comment]
Sorry for the spam! :sob:

**Comment by Gottox** [comment]
dmraid has still service files left over.

**Comment by xtraeme** [comment]
100% completed.
