### ISSUE TITLE
Tracking bug: change scm fetch methods to proper distfiles

### ISSUE THREAD

**Issue by beefcurtains** [voidlinux/void-packages#2070]
These packages invoke ``git clone``:

- [ ] a10disp: @xtraeme
- [ ] android-tools: @uggedal
- [ ] arm-mem-git: @xtraeme
- [ ] bbswitch: @xtraeme
- [ ] btrfs-progs: @xtraeme
- [ ] checkbashisms: @asergi
- [ ] clementine: @typhon
- [ ] compton-git: orphaned
- [ ] connman-ui-git: @xtraeme
- [ ] cppcheck: @xtraeme
- [ ] cubieboard2-uboot: @xtraeme
- [ ] docker: @xtraeme
- [ ] dssi-vst: @xtraeme
- [ ] dtc: @typhon
- [ ] dzen2: @xtraeme
- [ ] efivar: @xtraeme
- [ ] f2fs-tools: @xtraeme
- [ ] fakechroot: @xtraeme
- [ ] filteraudio-git: @teh-jazzman
- [ ] fs-utils: @xtraeme
- [ ] fuse-usmb: @xtraeme
- [ ] gitflow: @xtraeme
- [ ] cargo: @chneukirchen
- [ ] gcc-go: @xtraeme
- [ ] go: @dominikh
- [x] hugo: @typhon
- [ ] libgo: @xtraeme
- [x] ~~libreoffice-bin-i18n-dgo: @xtraeme~~ (false positive)
- [x] ~~pango: @xtraeme~~ (false positive)
- [x] ~~perl-Pango: orphaned~~ (false positive)
- [x] ~~python-Django: @uggedal~~ (false positive)
- [ ] xlogo: @chneukirchen
- [ ] google-fonts-ttf-git: @asergi
- [ ] gtk-theme-config: @xtraeme
- [ ] ioquake3-rpi: @xtraeme
- [ ] ipe: @chneukirchen
- [ ] libapp: @xtraeme
- [ ] libclc-git: @RealJohnGalt
- [ ] libdri2-git: @xtraeme
- [ ] libosmocore: @Gottox
- [ ] libump-git: @xtraeme
- [ ] libvdpau-va-gl: @xtraeme
- [ ] linux-firmware: @xtraeme
- [ ] linux-user-chroot: @xtraeme
- [ ] ls++-git: @Ypnose
- [ ] ltrace: @xtraeme
- [ ] luakit: @xtraeme
- [ ] monsterwm-git: @Ypnose
- [ ] mvwm-git: @ThomasAdam
- [ ] ndhc: @chneukirchen
- [ ] net-tools: @xtraeme
- [ ] netbsd-wtf: @xtraeme
- [ ] nim: @allan
- [ ] omxplayer: @xtraeme
- [ ] pixz: @xtraeme
- [ ] polkit-qt: @xtraeme
- [ ] polkit-qt5: @xtraeme
- [ ] primus: @xtraeme
- [ ] qjson: @xtraeme
- [ ] qtchooser: @xtraeme
- [ ] rdis-git: @xtraeme
- [x] runit-swap: @typhon
- [ ] skypetab-ng: @xtraeme
- [ ] snb-git: @uggedal
- [ ] socklog-void: @chneukirchen
- [ ] sunxi-mali: @xtraeme
- [ ] sunxi-tools: @xtraeme
- [ ] trace-cmd: @chneukirchen
- [ ] tty-clock-git: @Ypnose
- [ ] ttyload-git: @ThomasAdam
- [ ] urlmatch-git: @xtraeme
- [ ] valadoc-git: @xtraeme
- [x] vboot-utils: @Gottox
- [ ] vis-git: @uggedal
- [ ] xbps: @xtraeme
- [ ] xbps-static: @xtraeme
- [ ] xdg-utils: @xtraeme
- [ ] xdot: @xtraeme
- [ ] xf86-video-intel: @xtraeme
- [ ] xsecurelock
- [ ] yajl: @xtraeme
- [ ] yt-play: @xtraeme
- [x] ~~gyp-svn: @Gottox~~ (duplicate)

This one uses svn:

- [ ] gyp-svn: @Gottox

With this bug we make sure cachable distfiles are used and checksums are verified everywhere.

**Comment by Gottox** [comment]
I believe that we should get rid of the -git and -svn packages.

**Comment by thypon** [comment]
I don't see the need to drop "git clone" packages. Debian has alredy a working cache distfile.

**Comment by Gottox** [comment]
I wasn't talking about packages that use git clone, but those with a "-git" or "-svn" suffix.

**Comment by thypon** [comment]
@beefcurtains there is also subtle, but i need one patch from upstream to compile. The same for clementine.

**Comment by Gottox** [comment]
May you add the maintainers of the packages too? This would be really helpful.

**Comment by beefcurtains** [comment]
Done. I think I found a few orphans, they are marked as such. No idea who did xsecurelock.

**Comment by Gottox** [comment]
vboot-utils: http download has unstable shasums.

**Comment by Gottox** [comment]
trace-cmd: no http download available

**Comment by Ypnose** [comment]
I will work on my pkgs next week. I will have much more time to do it. :feelsgood:

**Comment by chneukirchen** [comment]
How was that list made?

cargo: the bootstrap calls git, I don't see yet how to bundle all deps.
xlogo: no git?
ipe: no git?
ndhc: waiting for tag (could move to tarballs tho)

**Comment by thypon** [comment]
yt-play is broken for me. We can remove imho. Not updated since 2013

**Comment by thypon** [comment]
Same for gyp-svn, the repository is broken and nobody seems to require it directly.

**Comment by thypon** [comment]
arm-mem-git isn't compilable right now with our toolchain,

**Comment by Gottox** [comment]
:+1: the removal

**Comment by uggedal** [comment]
android-tools has no alternative source afaik.

**Comment by thypon** [comment]
@uggedal isn't possible to download a snapshot tarball?

**Comment by maxice8** [comment]
packages that no longer git clone (should be ticked):
f2fs-tools
go
xdg-utils
linux-firmware
libvdpau-va-gl
compton-git

packages that no longer exist (should be removed):
linux-user-chroot
valadoc-git
tty-clock-git

@lemmi

**Comment by lemmi** [comment]
@maxice8 done, thx for the list.
