### ISSUE TITLE
Request for Packages: Assorted network auth and related

### ISSUE THREAD

**Issue by the-maldridge** [voidlinux/void-packages#3119]
Two of the sites I manage are considering a switch away from Ubuntu.  Void is currently the first choice do to the simplicity of maintenence and the use of LibreSSL (we value security very highly).  This list is the software that we have found to be missing in Void.  While we plan to package as much as possible on our own, this list is here in the even others wish to help out.  Package names are from Ubuntu but should be clear anyway.

Obviously not all can be packaged for Void, but I defer to the more senior members of the community to point those out.
- [ ] icinga2
- [ ] icingaweb2
- [x] lightdm-webkit-greeter
- [x] krb5-kdc
- [x] libpam-krb5
- [x] ~~shutter~~ (duplicate of #2929 )
- [x] krb5-admin-server
- [x] libpam-ldapd
- [ ] icinga2-ido-mysql
- [ ] nagios-nrpe-server
- [x] ~~nagios-plugins~~ (duplicate of #3858)
- [x] libsasl2-modules-gssapi-mit
- [ ] python-mysqldb
- [x] libpam-mount
- [x] ~~gap~~
- [x] spim
- [x] krb5-kdc-ldap
- [x] ~~nagios-nrpe-plugin~~ (duplicate of #3858)
- [x] google-chrome-stable
- [x] ~~libcrypt-openssl-bignum-perl~~ (Pending review of irssi)
- [x] ~~WPS Office~~ (duplicate of #1711)

**Comment by chneukirchen** [comment]
We have mit-krb5 (not newest version tho).

**Comment by the-maldridge** [comment]
@chneukirchen To my knowledge that contains the client programs, not the server ones.

**Comment by Vaelatern** [comment]
Working on `libpam-krb5` version 4.7.

**Comment by Vaelatern** [comment]
Working on pam-mount.

**Comment by EaterOfCode** [comment]
When monitoring plugins is through, I'll add Icinga (monitoring plugins is a dependecy of icinga)

**Comment by the-maldridge** [comment]
This ticket should have been closed ages ago.  All the core software we needed for our migration has been available for some time.
