### ISSUE TITLE
Tracking bug: unmarked non-PIE executables

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#4227]
These packages failed on a bulk build by @dominikh due to non-PIE executables, please ensure LDFLAGS are respected.

- [x] Ice
- [x] apg
- [x] bchunk
- [x] beep
- [x] bftpd
- [x] bglibs
- [x] bish
- [x] blktrace
- [x] bonnie++
- [x] boost
- [x] bsd-games
- [x] cdecl
- [x] cdrtools
- [x] chicken
- [x] cpulimit
- [x] crash
- [x] cross-aarch64-linux-gnu
- [x] cross-aarch64-linux-musl
- [x] cross-arm-linux-gnueabi
- [x] cross-arm-linux-gnueabihf
- [x] cross-arm-linux-musleabi
- [x] cross-arm-linux-musleabihf
- [x] cross-armv7l-linux-gnueabihf
- [x] cross-armv7l-linux-musleabihf
- [x] cross-i686-linux-musl
- [x] cross-i686-pc-linux-gnu
- [x] cross-mips-linux-musl
- [x] cross-mipsel-linux-musl
- [x] cross-mipsel-linux-muslhf
- [x] cross-x86_64-linux-musl
- [x] daemonize
- [x] detox
- [x] discount
- [x] dmd
- [x] dnsmap
- [x] docbook2mdoc
- [x] dos2unix
- [x] dumpet
- [x] ent
- [x] erlang
- [x] foremost
- [x] fpc
- [x] ftjam
- [x] halibut
- [x] hans
- [x] herbstluftwm
- [x] hnb
- [x] inspircd
- [x] ipvsadm
- [x] ired
- [x] iselect
- [x] jeti-filemanager
- [x] jhead
- [x] kcgi
- [x] ladspa-sdk
- [x] lpsolve
- [x] lsw
- [x] m2m-aligner
- [x] mkinitcpio-nfs-utils
- [x] mon
- [x] nawk
- [x] nethack
- [x] netpgpverify
- [x] nginx
- [x] nim
- [x] nvidia
- [x] nvidia340
- [x] ocaml
- [x] otpw
- [x] parrot
- [x] pdmenu
- [x] pigz
- [x] pmr
- [x] progress
- [x] radamsa
- [x] rover
- [x] rtmpdump
- [x] sbcl
- [x] shellcheck
- [x] sl
- [x] sloccount
- [x] spiped
- [x] sres
- [x] texi2mdoc
- [x] tgt
- [x] tinywm
- [x] uboot-mkimage
- [x] ucspi-ssl
- [x] unclutter
- [x] vanitygen
- [x] vmtouch
- [x] xa
- [x] xcalib
- [x] xsettingsd
- [x] xspringies
- [x] yeahconsole
- [x] zpaq

- - -

Second iteration:

- [x] clisp
- [x] clockspeed
- [x] cvm
- [x] cwm
- [x] gprolog
- [x] nix
- [x] ocaml-findlib
- [x] ocamlbuild
- [x] opam
- [x] polygen
- [x] xskat
- [x] z3

-------

Third iteration:

- [x] android-tools
- [x] arpwatch
- [x] autossh
- [ ] boswars
- [ ] brother-brscan3
- [x] camlp4
- [ ] celestia-glut
- [ ] celestia-gtk
- [x] darkplaces
- [x] efmd
- [x] ghostscript
- [x] gnurobbo
- [ ] gtk-theme-config
- [ ] hooktftp
- [x] latencytop
- [x] lshw
- [x] maxima
- [ ] nestopia
- [ ] openjdk
- [ ] openmpi
- [ ] opensonic
- [x] oue
- [x] p0f
- [x] plan9port
- [x] ppp
- [x] puzzles
- [x] qiv
- [ ] rdis-git
- [x] soulseekqt
- [x] sublime-text3
- [ ] swift
- [ ] syslinux
- [x] teeworlds
- [ ] tiv
- [x] ttyload-git
- [x] twoftpd
- [x] wm2
- [x] xbanish
- [x] xchat
- [x] xcolorsel
- [x] xlbiff
- [ ] xonotic
- [x] zerofree

-------

Found and fixed:

- [x] qt
- [x] qtchooser
- [x] NetworkManager
- [x] network-manager-applet

**Comment by pullmoll** [comment]
I tried several ways to get `ghostscript` binary `gsx` linked with our `LDFLAGS` to no avail. Perhaps someone with more insight manages to fix that one? I'm feeling stupid.
