### ISSUE TITLE
KDE 5

### ISSUE THREAD

**Issue by dutsky** [voidlinux/void-packages#4963]
KDE 5 divided in three parts: Frameworks(ex-kdelibs), Plasma(runtime) and Applications.
### Frameworks

Needed to build Plasma and Applications.
Many packages in this list must be built from top to down, because of dependencies
- [x] attica-qt5 -- already in repo
- [x] kapidox -- already in repo #4884 
- [x] karchive -- already in repo #4885 
- [x] kcodecs -- already in repo #4890 
- [x] kconfig -- already in repo #4895 
- [x] kcoreaddons -- already in repo #4896 
- [x] kdbusaddons -- already in repo #4901 
- [x] kdnssd -- already in repo #4919 
- [x] kguiaddons -- already in repo
- [x] ki18n -- already in repo #4920 
- [x] kidletime -- already in repo
- [x] kimageformats -- already in repo #4930 
- [x] kitemmodels -- already in repo #4921 
- [x] kitemviews -- already in repo #4922 
- [x] kplotting -- already in repo #4923 
- [x] kwidgetsaddons -- already in repo #4924 
- [x] kwindowsystem -- already in repo
- [x] networkmanager-qt5 -- already in repo #4925 
- [x] solid -- already in repo under "ksolid" name
- [x] sonnet -- already in repo #4928 
- [x] threadweaver -- already in repo #4929 
- [x] kauth -- already in repo #4931 
- [x] kcompletion -- already in repo #4957
- [x] kcrash -- already in repo #4957
- [x] kdoctools -- already in repo #4957
- [x] kpty -- already in repo #4942 
- [x] kunitconversion -- already in repo #4943 
- [x] kconfigwidgets -- already in repo #4957
- [x] kservice -- already in repo #4957
- [x] kglobalaccel -- already in repo #4957
- [x] kpackage -- already in repo #4957
- [x] kdesu -- already in repo #4957
- [x] kemoticons -- already in repo #4957
- [x] kiconthemes -- already in repo #4957
- [x] kjobwidgets -- already in repo #4957
- [x] knotifications -- already in repo #4957
- [x] ktextwidgets -- already in repo #4957
- [x] kwallet -- already in repo #4957
- [x] kxmlgui -- already in repo #4957
- [x] kbookmarks -- already in repo #4957
- [x] kio -- already in repo #4957
- [x] kdeclarative -- already in repo #4957
- [x] kcmutils -- already in repo #4957
- [x] frameworkintegration -- already in repo #4957
- [x] kinit -- already in repo #4957
- [x] knewstuff -- already in repo #4957
- [x] knotifyconfig -- already in repo #4957
- [x] kparts -- already in repo #4957
- [x] kactivities5 -- already in repo #4957
- [x] kded -- already in repo #4957
- [x] kdewebkit -- already in repo #4957
- [x] ktexteditor -- already in repo #4957
- [x] kdesignerplugin -- already in repo #4957
- [x] plasma-framework -- already in repo #4957
- [x] modemmanager-qt5 -- already in repo #4957
- [x] kpeople -- already in repo #4957
- [x] kxmlrpcclient -- already in repo #4957
- [x] bluez-qt5 -- already in repo #4957
- [x] kfilemetadata5 -- already in repo #4957
- [x] baloo5 -- already in repo #4957
- [x] breeze-icons -- already in repo
- [x] oxygen-icons5 -- already in repo #4957
- [x] kactivities5-stats -- already in repo #4957
- [x] krunner -- already in repo #4957
- [x] kwayland -- already in repo
- [x] kjs -- already in repo #4957
- [x] kdelibs4support -- already in repo #4957
- [x] khtml -- already in repo #4957
- [x] kjsembed -- already in repo #4957
- [x] kmediaplayer -- already in repo #4957
- [x] kross -- already in repo #4957
- [x] syntax-highlighting -- already in repo #5393

### Plasma

Shiny useless tools that load your cpu and gpu.
- [x] kde-cli-tools -- already in repo #5843
- [x] kdecoration -- already in repo#5843
- [x] libkscreen -- already in repo
- [x] libksysguard -- already in repo #5843
- [x] breeze -- already in repo #5843
- [x] breeze-gtk -- already in repo #5843
- [x] kscreenlocker -- already in repo #5843
- [x] oxygen -- already in repo #5843
- [x] kinfocenter -- already in repo #5843
- [x] ksysguard -- already in repo #5843
- [x] kwin -- already in repo #5843
- [x] systemsettings -- already in repo #5843
- [x] kactivitymanagerd -- already in repo #5843
- [x] milou -- already in repo  #5843
- [x] plasma-integration -- already in repo #5843
- [x] plasma-workspace -- already in repo #5843
- [x] bluedevil -- already in repo #5849
- [x] kde-gtk-config5 -- already in repo #5849
- [x] khotkeys -- already in repo #5849
- [x] kmenuedit -- already in repo #5849
- [x] kscreen -- already in repo #5849
- [x] kwallet-pam -- already in repo #5849
- [x] kwayland-integration -- already in repo #5849
- [x] kwrited -- already in repo #5849
- [x] plasma-nm -- already in repo #5849
- [x] plasma-pa -- already in repo #5849
- [x] plasma-workspace-wallpapers -- already in repo #5849
- [x] polkit-kde-agent -- already in repo #5849
- [x] powerdevil -- already in repo #5849
- [x] plasma-desktop -- already in repo #5849
- [x] kdeplasma-addons5 -- already in repo #5850
- [x] kgamma5 -- already in repo #5850
- [x] ksshaskpass -- already in repo #5850
- [x] plasma-sdk -- already in repo #5850
- [x] sddm-kcm -- already in repo #5850
- [x] user-manager -- already in repo #5850
### Applications
- [x] kholidays (needed for plasma-workspace) -- already in repo  #5843
- [x] konsole5 -- PR #7748
- [x] dolphin -- PR #7750
- [x] kate5 -- PR #7780
- [x] khelpcenter -- PR #7781
### How to sell your soul to the devil
- [x] kde5 (meta) -- PR #5850
- [x] kde5-baseapps (meta) -- PR #7782

**Comment by Vaelatern** [comment]
I hate to ask this, but which PRs have which packages?

**Comment by dutsky** [comment]
I'm just trying to understand how to edit text here :D I'll try to add PRs here now.

**Comment by dutsky** [comment]
What do you think is better for you: put one template in one PR or just make one PR with multiple commits(templates)? Thanks

**Comment by Vaelatern** [comment]
How many templates are we talking about? What sort of size of packages?

**Comment by Vaelatern** [comment]
but I'd recommend waiting on Plasma until the first step is fully merged, so PRs don't fail.

**Comment by dutsky** [comment]
Like additional ~40 packages (sorry), listed here. Yes-yes, i'm not in hurry, just curious.

**Comment by Vaelatern** [comment]
Monster PRs are less fun; but if A depends on B, for any given A or B in Plasma, they should be in the same PR. Beyond that, whether to trend to large PRs, middle sized PRs that stay on one sort of component within Plasma, or per-package PRs, I don't have a strong opinion.

**Comment by pullmoll** [comment]
You may have noticed me fixing cross building for most (all?) KDE5 packages in the repo.
The rule of thumb is to add `qt5-host-tools` to the `hostmakedepends`, as well as the qt5 package(s) which are in the `makedepends`.

Adding these extra bits could also be done inside an
```
if [ "$CROSS_BUILD" ]; then
...
fi
```
as I did for `sonnet`, which requires the native built `sonnet` pkg to import a host tool.

**Comment by Hoshpak** [comment]
@dutsky Is there anything I could maybe help with regarding this issue? Since KDE 4 experienced a degradation in functionality (see #5559) after the last KDE rebuild, it would be nice to get KDE 5 into Void to have a viable replacement for people wanting to use KDE.

**Comment by kachsheev** [comment]
What about Krusader and Kdevelop? These apps use currently KF5.

**Comment by dutsky** [comment]
I'm sorry about that guys, i'm on business trip and don't have much time for it now. I've already have all template files for plasma in my "plasma" branch, but last time i've check it i had some issues with kde starting and it was hard to debug for me. It must be dependencies problem I think, but I'll try to check it out when I return. 
About Krusader and Kdevelop, it must not be hard to create template files, if it already using KF5, it's just time consuming.

**Comment by weabot** [comment]
Will plasma be kept on LTS? It would take much less maintenance.

**Comment by dutsky** [comment]
It is good idea, but i can't promise anything. I will wonder if KDE5 will run well on void linux one day.

**Comment by silvernode** [comment]
I can I like...donate or something to speed this up? Used Fedora with plasma5 for the last 4 months, but Fedora was slow for me (although I did enjoy it) so now I am running Chakra and having a terrible time with package availability. I really want to go back to Void because it has the packages I want (some of which I packaged myself) but I would really like to keep my workflow going with Plasma5. I know this suite is a lot of work but if there is anything I can do non-codewise, I will do what I can.

**Comment by dutsky** [comment]
Hello, dear silvernode! All I can do is to suggest you to build from sources. It must be not hard, but very time consuming.

You can do this by typing this commands(assume you have ~/devel):
cd ~/devel
git clone https://github.com/dutsky/void-packages.git
cd void-packages
git checkout plasma
./xbps-pkg binary-bootstrap
./xbps-pkg pkg kde5 (it will take a **LOT** of time, like several hours)
xbps-install --repository=hostdir/binpkgs/plasma kde5
sudo ln -s /etc/sv/dhcpd /var/service
sudo ln -s /etc/sv/sddm /var/service

and reboot, if sddm didn't started

**Comment by Vaelatern** [comment]
@dutsky can you recommend a fix for a particular problem we have? If we use one URL, we see the kde5 archives, but not the latest version. If we use another URL, we only see the latest version. This breaks rebuilds without bumps. With this fixed, I think a lot more of KDE5 can be merged.

**Comment by Vaelatern** [comment]
Merged one, will review the other and hopefully merge so this can stop rotting in the PRs.
Thank you for all your work!

**Comment by dutsky** [comment]
No, you!

**Comment by silvernode** [comment]
@dutsky Thank you very much for the useful and hopeful reply. I will go ahead and try building plasma for myself from your fork once I get the time. It looks like I got the conversation here started again. We really need plasma5 in void as it's quickly becoming a sweet desktop for a lot of people. I can test out whatever anyone needs me to test if it comes down to that. cheers!

**Comment by dutsky** [comment]
@silvernode, Vaelatern already started merging plasma, if it will be ok, you don't need to build it from the sources. 
There are some musl-related problems, but i'll try to resolve it later. 
And be ready to a lot of bugs, because I always mess up :)

**Comment by silvernode** [comment]
@dutsky Thank you very much for the useful and hopeful reply. I will go ahead and try building plasma for myself from your fork once I get the time. It looks like I got the conversation here started again. We really need plasma5 in void as it's quickly becoming a sweet desktop for a lot of people. I can test out whatever anyone needs me to test if it comes down to that. cheers!

**Comment by silvernode** [comment]
@dutsky It's ok with me if there are some bugs, I will make sure to report anything I find once things get merged. I'll just be glad to use it.

**Comment by mstraube** [comment]
@dutsky First thanks for all your work! I packaged some KDE5 applications based on your templates. They are in the kde-applications branch of my fork, feel free to use them. I hope it helps a little getting a nice Plasma5 experience.

**Comment by dutsky** [comment]
@mstraube thank you, but thanking me is unwanted 😊 , because my work sucks and I not smart enough to do it right :D 
I will try to use it, thanks!

**Comment by logenkain** [comment]
On Thu, Sep 21, 2017 at 05:14:33PM +0000, dut wrote:
> @mstraube thank you, but thanking me is unwanted 😊 , because my work sucks and I not smart enough to do it right :D 
> I will try to use it, thanks! 
> 

Don't worry, we're all imposters here ^_^

**Comment by dutsky** [comment]
![I'm retarded](http://www.kittyworks.com/images/jz043bdh0v5.jpg)

**Comment by Chocimier** [comment]
@mstraube, do you plan to push your kde applications to main repo?

**Comment by adomas187** [comment]
Would be cool to have also **Gwenview** (Image Viewer) app from _KDE Apps_:
https://www.kde.org/applications/graphics/gwenview/

As for now, there is no alternative to view photos/images in KDE Plasma desktop... Now I'm forced to use Chromium :smile: 

Even better would be **digiKam** (https://www.digikam.org/) which has **ShowFoto** as part of it.

**Comment by Hoshpak** [comment]
I've submitted a PR for Gwenview in #10110 . I also looked at digiKam but that software is way too complex, I wouldn't be comfortable maintaining that package.

**Comment by adomas187** [comment]
@Hoshpak Thank you for Gwenview! Really appreciate it. Hope to see it in repos soon :+1: 

About digiKam, yes it's pretty complex. It is fully featured photo management tool, with loads of fancy features. Anyway more important is Gwenview for basic photo viewing.

**Comment by mstraube** [comment]
Just for information: All packages from my kde-applications branch are in the repos now, deleted the branch.
