### ISSUE TITLE
Tracking bug: Server infrastructure move TODO

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/void-packages#5449]
Various things that need fixing someday:

- [x] update xlocate
- [x] update void-updates.txt
- [x] Tor?
- [x] shorter IRC messages from buildbot

**Comment by Gottox** [comment]
* [ ] properly fix signing

**Comment by ebfe** [comment]
* [ ] actually move new aarch64/musl packages into the repo

**Comment by the-maldridge** [comment]
I motion to not reinstate tor unless there is an actual downstream user that can be shown to be using it.  We have enough issues already and don't need to add additional complexity right now.

**Comment by Duncaen** [comment]
* [ ] rsyncd, repo2 and kc are outdated.

**Comment by the-maldridge** [comment]
kc is updating now.  I changed the name on the rsyncd stanza without thinking about the other mirrors.

**Comment by the-maldridge** [comment]
@chneukirchen The buildbot configuration is committed at https://github.com/the-maldridge/void-infrastructure/blob/root-mirror/roles/buildmaster/templates/master.cfg.j2  PR is welcome to change the IRC message format.

**Comment by Gottox** [comment]
* [ ] signing is broken:

```
[root@build bin]# cat /etc/cron.d/buildmaster_repomgmt 
* * * * * void-repomaster ${HOME}/bin/xbps-sign-repos.sh >/dev/null 2>&1
0 2 * * * void-repomaster ${HOME}/bin/xbps-clean-repos.sh
```
The scripts can't be found, because they don't have the `.sh` suffix. Corrected version:
```
[root@build bin]# cat /etc/cron.d/buildmaster_repomgmt 
* * * * * void-repomaster ${HOME}/bin/xbps-sign-repos >/dev/null 2>&1
0 2 * * * void-repomaster ${HOME}/bin/xbps-clean-repos
```

**Comment by Gottox** [comment]
* [ ] wrong permissions of /usr/lib/python2.7/site-packages/zope.event-4.2.0.dist-info: no perms for ```o```

**Comment by the-maldridge** [comment]
@Gottox I'm inclined to say that's a package error, I had similar issues with the buildmaster which is why its a virtualenv install (I assume this is on the buildslave)

**Comment by Gottox** [comment]
I've never experienced it before. maybe a umask issue?

**Comment by the-maldridge** [comment]
Plausible, @dinoocch, can you weigh in on this?

**Comment by ebfe** [comment]
- [ ] .xz, .xbps, .sig are served with content-type text/html

**Comment by the-maldridge** [comment]
@ebfe, changing that as we speak.

**Comment by the-maldridge** [comment]
@Gottox Signing filename now fixed.

**Comment by the-maldridge** [comment]
@ebfe the default_type is now application/octet-stream

**Comment by chneukirchen** [comment]
[ ] aarch64 packages have not been signed back to Jan 3.

**Comment by the-maldridge** [comment]
@chneukirchen tor has been up and running for a few days now, can we go ahead and check that off?

**Comment by Gottox** [comment]
* [ ] sources.voidlinux.eu is missing ssl.

**Comment by the-maldridge** [comment]
@Gottox sources.voidlinux.eu now has SSL
